using System.Collections.Immutable;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Text;
using Microsoft.CodeAnalysis.Text;

namespace MyManager.SourceGenerators;

[Generator]
public sealed class IsomorphSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "MyManager.Attributes";
    private const string AttributeName = "IsomorphAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                (s, _) => s is RecordDeclarationSyntax,
                (ctx, _) => GetClassDeclarationForSourceGen(ctx))
            .Where(t => t.attributeFound)
            .Select((t, _) => t.Item1);

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            ((ctx, t) => GenerateCode(ctx, t.Left, t.Right)));
    }

    private static (RecordDeclarationSyntax, bool attributeFound) GetClassDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (RecordDeclarationSyntax)context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in classDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (context.SemanticModel.GetSymbolInfo(attributeSyntax).Symbol is not IMethodSymbol attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            string attributeName = attributeSymbol.ContainingType.ToDisplayString();

            if (attributeName == $"{Namespace}.{AttributeName}")
                return (classDeclarationSyntax, true);
        }

        return (classDeclarationSyntax, false);
    }

    private void GenerateCode(SourceProductionContext context, Compilation compilation,
                              ImmutableArray<RecordDeclarationSyntax> declarations)
    {
        // Go through all filtered class declarations.
        foreach (var declSyntax in declarations)
        {
            // We need to get semantic model of the class to retrieve metadata.
            var semanticModel = compilation.GetSemanticModel(declSyntax.SyntaxTree);

            // Symbols allow us to get the compile-time information.
            if (semanticModel.GetDeclaredSymbol(declSyntax) is not { } symbol)
                continue;

            var namespaceName = symbol.ContainingNamespace.ToDisplayString();

            var recordClassOrRecordStruct =
                declSyntax.Kind() is SyntaxKind.RecordDeclaration ? "record" : "record struct";

            // 'Identifier' means the token of the node. Get class-name from the syntax node.
            var recordName = declSyntax.Identifier.Text;

            var isSealed = declSyntax.Modifiers.Any(m => m.IsKind(SyntaxKind.SealedKeyword));

            // Get the primary constructor (the implicitly declared one with parameters)
            var primaryConstructor = symbol.Constructors
                .FirstOrDefault(c => c.Parameters.Any());

            if (primaryConstructor is null)
                continue; // Skip if no primary constructor (e.g., record with no parameters)

            var parameters = primaryConstructor.Parameters;

            var sealedKeyword = isSealed ? "sealed " : "";
            var parameterTypes = parameters.Select(p => $"{p.Type} {p.Name.First().ToString().ToLower() + p.Name.Substring(1)}");
            var parametersString = string.Join(", ", parameterTypes);
            var args = string.Join(", ", parameters.Select(p => p.Name.First().ToString().ToLower() + p.Name.Substring(1)));

            var unapplyMethodReturnType =
                parameters.Length == 1 ?
                    parameters.First().Type.ToDisplayString() :
                    $"({string.Join(", ", parameters.Select(p => p.Type))})";

            var unapplyString =
                parameters.Length == 1 ?
                    $"self.{parameters.First().Name}" :
                $"({string.Join(", ", parameters.Select(p => $"self.{p.Name}"))})";

            var code =
                $$"""
                  // <auto-generated/>
                  
                  namespace {{namespaceName}};

                  {{sealedKeyword}}partial {{recordClassOrRecordStruct}} {{recordName}}
                  {
                      public static {{recordName}} Apply({{parametersString}})
                      {
                          return new({{args}});
                      }
                      
                      public static {{unapplyMethodReturnType}} Unapply({{recordName}} self)
                      {
                          return {{unapplyString}};
                      }
                  }

                  """;

            // Add the source code to the compilation.
            context.AddSource($"{recordName}.Isomorph.g.cs", SourceText.From(code, Encoding.UTF8));
        }
    }
}
