using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MyManager.SourceGenerators;

[Generator]
public sealed class ModuleSourceGenerator : IIncrementalGenerator
{
    private const string ModuleNamespace = "MyManager.Http";
    private const string ModuleClassName = "IModule";
    private const string ModuleFullName = $"{ModuleNamespace}.{ModuleClassName}";

    private const string Namespace = "MyManager.Http";
    private const string ModuleExtensionsClassName = "ModuleExtensions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider.CreateSyntaxProvider(
            (node, _) => node is ClassDeclarationSyntax,
            (ctx, _) => (ClassDeclarationSyntax)ctx.Node
        ).Where(x => x is not null);

        var compilation = context.CompilationProvider.Combine(provider.Collect());

        context.RegisterSourceOutput(compilation, (spc, src) => Execute(spc, src.Left, src.Right));
    }

    private static void Execute(SourceProductionContext context, Compilation compilation,
                                ImmutableArray<ClassDeclarationSyntax> classes)
    {
        if (classes.IsEmpty)
            return;


        var iModuleSymbol = compilation.GetTypeByMetadataName(ModuleFullName);
        if (iModuleSymbol is null)
            return;


        List<INamedTypeSymbol> matchingClasses = [];

        foreach (var classDecl in classes)
        {
            var model = compilation.GetSemanticModel(classDecl.SyntaxTree);

            if (model.GetDeclaredSymbol(classDecl) is not INamedTypeSymbol symbol)
                continue;

            var implementsInterface =
                symbol.AllInterfaces.Any(i => SymbolEqualityComparer.Default.Equals(i, iModuleSymbol));

            if (!implementsInterface)
                continue;

            matchingClasses.Add(symbol);
        }

        GenerateModuleExtensionsCode(context, matchingClasses.ToImmutableArray());
    }

    public static void GenerateModuleExtensionsCode(SourceProductionContext context,
                                                     ImmutableArray<INamedTypeSymbol> classes)
    {
        var registerModuleServices = classes.Select(c => $"new {c.ToDisplayString()}().RegisterServices(builder);");
        var useModuleMiddleware = classes.Select(c => $"new {c.ToDisplayString()}().UseMiddleware(app);");
        var mapModuleEndpoints = classes.Select(c => $"new {c.ToDisplayString()}().MapEndpoints(app);");

        var source =
            $@"  // <auto-generated/>
  namespace {Namespace};

  public static partial class ModuleExtensions {{
      public static WebApplicationBuilder RegisterModuleServices(this WebApplicationBuilder builder)
      {{
          {string.Join("\n", registerModuleServices)}
          return builder;
      }}
      
      public static WebApplication UseModuleMiddleware(this WebApplication app)
      {{
          {string.Join("\n", useModuleMiddleware)}
          return app;
      }}
      
      public static IEndpointRouteBuilder MapModuleEndpoints(this IEndpointRouteBuilder app) {{
          {string.Join("\n", mapModuleEndpoints)}
          return app;
      }}
  }}
";

        context.AddSource($"{ModuleExtensionsClassName}.g.cs", SourceText.From(source, Encoding.UTF8));
    }
}
