using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace MyManager.SourceGenerators;

[Generator]
public sealed class RegisterServicesSourceGenerator : IIncrementalGenerator
{
    private const string Namespace = "MyManager.Attributes";
    private const string RegisterScopedAttribute = "RegisterScopedAttribute";
    private const string RegisterSingletonAttribute = "RegisterSingletonAttribute";
    private const string RegisterTransientAttribute = "RegisterTransientAttribute";

    private const string TargetNamespace = "MyManager.Services";
    private const string TargetClassName = "RegisterServicesExtensions";

//     private const string AttributesSource =
//         """
//         // <auto-generated/>
//
//         #nullable enable
//
//         namespace MyManager.Attributes;
//
//         [System.AttributeUsage(System.AttributeTargets.Class)]
//         public partial class RegisterScopedAttribute(System.Type? type = null): System.Attribute;
//
//         [System.AttributeUsage(System.AttributeTargets.Class)]
//         public partial class RegisterSingletonAttribute(System.Type? type = null) : System.Attribute;
//
//         [System.AttributeUsage(System.AttributeTargets.Class)]
//         public partial class RegisterTransientAttribute(System.Type? type = null) : System.Attribute;
//
//         """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // context.RegisterPostInitializationOutput(ctx =>
        //     ctx.AddSource("RegisterAttributes.g.cs", SourceText.From(AttributesSource, Encoding.UTF8))
        // );

        var provider = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsCandidate(s),
                (ctx, _) => GetDeclarationForSourceGen(ctx))
            .Where(static t => t.attributeFound)
            .Select(static (t, _) => t.Item1);

        // Generate the source code.
        context.RegisterSourceOutput(context.CompilationProvider.Combine(provider.Collect()),
            (ctx, t) => GenerateCode(ctx, t.Left, t.Right));
    }


    private static bool IsCandidate(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax;
    }

    private static (ClassDeclarationSyntax, bool attributeFound) GetDeclarationForSourceGen(
        GeneratorSyntaxContext context)
    {
        var classDeclarationSyntax = (ClassDeclarationSyntax) context.Node;

        // Go through all attributes of the class.
        foreach (AttributeListSyntax attributeListSyntax in classDeclarationSyntax.AttributeLists)
        foreach (AttributeSyntax attributeSyntax in attributeListSyntax.Attributes)
        {
            if (ModelExtensions.GetSymbolInfo(context.SemanticModel, attributeSyntax).Symbol is not IMethodSymbol
                attributeSymbol)
                continue; // if we can't get the symbol, ignore it

            var attributeName = attributeSymbol.ContainingType.ToDisplayString();

            if (attributeName is $"{Namespace}.{RegisterScopedAttribute}" or $"{Namespace}.{RegisterSingletonAttribute}"
                or $"{Namespace}.{RegisterTransientAttribute}")
                return (classDeclarationSyntax, true);
        }

        return (classDeclarationSyntax, false);
    }

    private static void GenerateCode(SourceProductionContext context, Compilation compilation,
                                     ImmutableArray<ClassDeclarationSyntax> classDeclarations)
    {
        var registrations = new List<string>();

        foreach (var classDeclarationSyntax in classDeclarations)
        {
            // We need to get semantic model of the class to retrieve metadata.
            var semanticModel = compilation.GetSemanticModel(classDeclarationSyntax.SyntaxTree);

            // Symbols allow us to get the compile-time information.
            if (semanticModel.GetDeclaredSymbol(classDeclarationSyntax) is not { } classSymbol)
                continue;

            foreach (var attribute in classSymbol.GetAttributes())
            {
                var lifetime = attribute.AttributeClass?.Name switch
                {
                    RegisterScopedAttribute    => "Scoped",
                    RegisterSingletonAttribute => "Singleton",
                    RegisterTransientAttribute => "Transient",
                    _                          => "Scoped",
                };

                INamedTypeSymbol? type = null;

                type = attribute.ConstructorArguments.Length > 0 && !attribute.ConstructorArguments[0].IsNull
                    ? attribute.ConstructorArguments[0].Value as INamedTypeSymbol
                    : classSymbol.Interfaces.FirstOrDefault();

                registrations.Add(
                    type is not null
                        ? $"services.Add{lifetime}<{type.ToDisplayString()}, {classSymbol.ToDisplayString()}>();"
                        : $"services.Add{lifetime}<{classSymbol.ToDisplayString()}>();");
            }
        }

        var registrationsString = string.Join("\n", registrations);

        // Build up the source code
        var code =
            $$"""
              // <auto-generated/>

              using System;
              using System.Collections.Generic;
              using Microsoft.Extensions.DependencyInjection;
              
              namespace {{TargetNamespace}};

              public static partial class {{TargetClassName}}
              {
                  public static IServiceCollection RegisterAutoServices(this IServiceCollection services)
                  {
                      {{registrationsString}}
                      
                      return services;
                  }
              }

              """;

        // Add the source code to the compilation.
        context.AddSource($"{TargetClassName}.g.cs", SourceText.From(code, Encoding.UTF8));
    }
}
